# basic

In [1]:
import torch 
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd

### scalar

In [2]:
scalar = torch.tensor(1)
print(scalar)
print(scalar.shape)
print(scalar.ndim)

tensor(1)
torch.Size([])
0


### vector

In [3]:
vector = torch.tensor([1,1])
print(vector)
print(vector.shape)
print(vector.ndim)

tensor([1, 1])
torch.Size([2])
1


### matrix

In [4]:
matrix = torch.tensor([[1, 1, 1],
                      [1, 1, 1]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)

tensor([[1, 1, 1],
        [1, 1, 1]])
torch.Size([2, 3])
2


### tensor

In [5]:
tensor = torch.tensor([[[1, 1],
                        [1, 1]],
                       
                       [[1, 1],
                        [1, 1]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])
torch.Size([2, 2, 2])
3


### random tensors

In [6]:
random_tensor = torch.rand(3, 2)
print(random_tensor)
random_tensor = torch.rand(size=(3, 2))
print(random_tensor)

tensor([[0.9719, 0.4043],
        [0.9685, 0.3354],
        [0.5648, 0.5018]])
tensor([[0.4281, 0.2597],
        [0.8211, 0.3591],
        [0.3676, 0.0994]])


### zero and one tensor

In [7]:
zero = torch.zeros(3, 2)
print(zero)
one = torch.ones(3, 2)
print(one)
print(one * random_tensor)
print(one.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.4281, 0.2597],
        [0.8211, 0.3591],
        [0.3676, 0.0994]])
torch.float32


In [8]:
tensor = torch.arange(0, 24, 2)
print(tensor)
print(tensor.reshape(2, 2, 3))
print(tensor.reshape(4, 3))

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])
tensor([[[ 0,  2,  4],
         [ 6,  8, 10]],

        [[12, 14, 16],
         [18, 20, 22]]])
tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16],
        [18, 20, 22]])


In [9]:
# createing tensor with shape like another tensor
tensor = tensor.reshape(4, 3)
print(tensor.shape)
print(torch.zeros_like(input=tensor))
print(torch.rand_like(input=tensor.float())) # here we have to convert data do float numbers
print(torch.ones_like(input=tensor))

torch.Size([4, 3])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0.5724, 0.2604, 0.5415],
        [0.8294, 0.1716, 0.9577],
        [0.1944, 0.1948, 0.6674],
        [0.5423, 0.9265, 0.8420]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


### datatypes

In [10]:
float32_tensor = torch.tensor([0.2, 0.6, 5.3])
print(float32_tensor)
float16_tensor = torch.tensor([0.2, 0.6, 5.3], dtype=torch.float16)
print(float16_tensor)
tensor = torch.tensor([0.2, 0.6, 5.3],
                      dtype = None, #default float32
                      device = "cuda", #default cpu
                      requires_grad=False) # track or not gradients
print(tensor)
print(float16_tensor * float32_tensor)
                      

tensor([0.2000, 0.6000, 5.3000])
tensor([0.2000, 0.6001, 5.3008], dtype=torch.float16)
tensor([0.2000, 0.6000, 5.3000], device='cuda:0')
tensor([ 0.0400,  0.3601, 28.0941])


### manipulationg tensors

In [11]:
Mat1, Mat2 = torch.rand(2, 2), torch.eye(2, 2)
print(Mat1)
print(Mat2)
print()
print(Mat1 + Mat2)
print()
print(Mat1 - Mat2)
print()
print(Mat1 * Mat2)
print()
print(Mat1 @ Mat2)

tensor([[0.6458, 0.6033],
        [0.5987, 0.3069]])
tensor([[1., 0.],
        [0., 1.]])

tensor([[1.6458, 0.6033],
        [0.5987, 1.3069]])

tensor([[-0.3542,  0.6033],
        [ 0.5987, -0.6931]])

tensor([[0.6458, 0.0000],
        [0.0000, 0.3069]])

tensor([[0.6458, 0.6033],
        [0.5987, 0.3069]])


In [12]:
Mat1 = torch.rand(3)
Mat2 = torch.rand(3)
print(Mat1 @ Mat2) # for vectors it works because it performes dot product 
Mat1 = torch.rand(1, 2)
Mat2 = torch.rand(2, 3)
print(Mat1 @ Mat2)
Mat1 = torch.rand(1, 3)
Mat2 = torch.rand(3, 1)
print(Mat1 @ Mat2)
print((Mat1 @ Mat2).shape)

tensor(0.7808)
tensor([[0.5609, 1.2170, 0.7923]])
tensor([[0.4127]])
torch.Size([1, 1])


### tensor aggregation

In [13]:
tensor = torch.rand(20, 20)
print(tensor.min())
print(tensor.max())
print(tensor.mean())
print(tensor.sum())
print()
print(tensor.argmax())
print(torch.unravel_index(tensor.argmax(), tensor.shape))
print(tensor.argmin())
print(torch.unravel_index(tensor.argmin(), tensor.shape))
tensor[torch.unravel_index(tensor.argmin(), tensor.shape)]
tensor[(6, 11)], tensor[6][11]


tensor(0.0009)
tensor(0.9999)
tensor(0.4870)
tensor(194.8022)

tensor(38)
(tensor(1), tensor(18))
tensor(10)
(tensor(0), tensor(10))


(tensor(0.8004), tensor(0.8004))

### reshaping, stacking, squeezing, unsqueezing

In [14]:
x = torch.arange(1, 11)
print(x, x.shape)
print(x.reshape(2, 5), x.reshape(2, 5).shape)
print()

print(torch.stack([x, x, x, x]))
print(torch.stack([x, x, x, x], dim=1))
print()

y = torch.arange(1, 11)
y = y.reshape(10, 1)
x = x.unsqueeze(dim=0)
print(x.shape, y.shape)
print(x @ y)
print((x @ y).shape)
print((x @ y).squeeze())
print((x @ y).squeeze().shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) torch.Size([2, 5])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

torch.Size([1, 10]) torch.Size([10, 1])
tensor([[385]])
torch.Size([1, 1])
tensor(385)
torch.Size([])


In [15]:
x = torch.rand(2, 3, 4)
print(x, x.shape, '\n')

y = x.permute(2, 1, 0)
print(y, y.shape, '\n')

z = x.permute(1, 0, 2)
print(z, z.shape, '\n')


tensor([[[0.0700, 0.6815, 0.5066, 0.3229],
         [0.6302, 0.1066, 0.2030, 0.0174],
         [0.5114, 0.7140, 0.2446, 0.0842]],

        [[0.9159, 0.3338, 0.2484, 0.8854],
         [0.9144, 0.8635, 0.0762, 0.9263],
         [0.5593, 0.7703, 0.7516, 0.3442]]]) torch.Size([2, 3, 4]) 

tensor([[[0.0700, 0.9159],
         [0.6302, 0.9144],
         [0.5114, 0.5593]],

        [[0.6815, 0.3338],
         [0.1066, 0.8635],
         [0.7140, 0.7703]],

        [[0.5066, 0.2484],
         [0.2030, 0.0762],
         [0.2446, 0.7516]],

        [[0.3229, 0.8854],
         [0.0174, 0.9263],
         [0.0842, 0.3442]]]) torch.Size([4, 3, 2]) 

tensor([[[0.0700, 0.6815, 0.5066, 0.3229],
         [0.9159, 0.3338, 0.2484, 0.8854]],

        [[0.6302, 0.1066, 0.2030, 0.0174],
         [0.9144, 0.8635, 0.0762, 0.9263]],

        [[0.5114, 0.7140, 0.2446, 0.0842],
         [0.5593, 0.7703, 0.7516, 0.3442]]]) torch.Size([3, 2, 4]) 



### indexing

In [34]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print()
print(x[0][0])
print(x[0, 1])
print(x[:, 0])
print(x[0, :, 0])
print(x[0, 1:, 0])
print(x[:, 0:1, 0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([[1, 2, 3]])
tensor([1, 4, 7])
tensor([4, 7])
tensor([[1]])


### numpy

In [37]:
array = np.arange(1.0, 8.0)
print(array)
tensor = torch.from_numpy(array)
print(tensor)
array.dtype

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


dtype('float64')

In [38]:
print(tensor)
array += 1
print(tensor)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [42]:
tensor = torch.ones(7)
array = tensor.numpy()
print(tensor, array)
tensor += 1
print(tensor, array)
print(id(tensor) == id(array))


tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2. 2. 2.]
False


### reproducibility

In [47]:
x = torch.rand(3, 4)
y = torch.rand(3, 4)
print(x)
print(y)
print(x == y)
print()

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
x = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
y = torch.rand(3, 4)
print(x)
print(y)
print(x == y)


tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## CUDA

In [51]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device #ezz

'cuda'

In [55]:
tensor = torch.arange(0, 10, device=device)
print(tensor)
tensor = torch.arange(0, 10)
print(tensor)
tensor = tensor.to(device)
print(tensor)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')


In [60]:
# tensor.numpy() error numpy works on cpu
array = tensor.to('cpu').numpy()
print(array)
array = tensor.cpu().numpy() #also works
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
